version: '3.7'
services:
  myapp:
    image: app:latest
    container_name: myapp
    environment:
      - DB_HOST=mydb
      - DB_PORT=5432
  mydb:
    image: postgres:latest
    container_name: mydb
    environment:
      - POSTGRES_USER=lotto
      - POSTGRES_PASSWORD=lotto
      - POSTGRES_DB=lotto
    ports:
      - 5433:5432
  localstack:
    image: localstack/localstack
    container_name: mylocalstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,lambda,serverless,sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=application
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"